server:
  port : 8081

spring:
  jpa:
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    url: jdbc:postgresql://localhost:5432/rpc
    username: binneling
    password: hemmelig
    driver-class-name: org.postgresql.Driver


rpc:
  teams:
    testTeam: localhost